name: 02 - Workflow Events

on:
  workflow_dispatch:
    inputs:
      user_input:
        description: 'Enter a number between 1-10'
        required: true

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "I've been triggered by a(n) ${{ github.event_name }} event."

      - name: display the input
        run: |
          echo "User entered: ${{ github.event.inputs.user_input }}"